/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import javax.swing.table.DefaultTableModel;
import model.Guitar;
import model.GuitarInventory;
import controller.GuitarController;
import javax.swing.JOptionPane;
/**
 *
 * @author Dell
 */
public class HomePage extends javax.swing.JFrame {
    private DefaultTableModel tableModel;
    private GuitarController controller;
    private String role;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HomePage.class.getName());

    /**
     * Creates new form HomePage
     */
    public HomePage() {
    this(new GuitarController(new GuitarInventory()), "ADMIN");
    }

    public HomePage(GuitarController controller) {
    this(controller, "ADMIN");
    }

    public HomePage(GuitarController controller, String role) {
    initComponents();
    this.controller = controller;
    this.role = role;

    setupTable();
    seedInitialData();
    loadTableFromInventory();

    applyRoleAccess(); 
    
    if ("USER".equalsIgnoreCase(role)) {
    int idx = jTabbedPane1.indexOfComponent(jPanel2); // Browse Guitars panel
    if (idx != -1) {
        jTabbedPane1.setSelectedIndex(idx);
    }
    }
    }
    private void loadTableFromList(java.util.List<Guitar> list) {
    tableModel.setRowCount(0);

    for (Guitar g : list) {
        tableModel.addRow(new Object[]{
            g.getGuitarId(),
            g.getBrand(),
            g.getType(),
            g.getYear(),
            g.getPrice()
        });
    }
}
    private void applyRoleAccess() {
    boolean isAdmin = "ADMIN".equalsIgnoreCase(role);

    // Admin-only actions
    jButtonAdd.setEnabled(isAdmin);
    jButtonUpdate.setEnabled(isAdmin);
    jButtonDelete.setEnabled(isAdmin);
    jButtonUndo.setEnabled(isAdmin);

    // Everyone can sort
    jButtonSortAsc.setEnabled(true);
    jButtonSortDesc.setEnabled(true);

    // Input fields: admin can type, user can't
    jTextField1.setEnabled(isAdmin);
    jTextField5.setEnabled(isAdmin);
    jTextField6.setEnabled(isAdmin);
    jTextField2.setEnabled(isAdmin);
    jTextField4.setEnabled(isAdmin);

    // Optional: if user, force them to Browse tab first
    if (!isAdmin) {
        int idx = jTabbedPane1.indexOfComponent(jPanel2); // your table tab
        if (idx != -1) jTabbedPane1.setSelectedIndex(idx);
    }
}





    private void setupTable() {
    tableModel = new DefaultTableModel(
        new String[]{"Guitar ID", "Brand", "Type", "Year", "Price"}, 0
    ) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; 
        }
    };
    jTable1.setModel(tableModel);
    jTable1.getTableHeader().setReorderingAllowed(false);

}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonDelete = new javax.swing.JButton();
        jButtonSortAsc = new javax.swing.JButton();
        jButtonSortDesc = new javax.swing.JButton();
        jButtonUndo = new javax.swing.JButton();
        jButtonSearch = new javax.swing.JButton();
        jTextFieldSearch = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButtonAdd = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel4.setBackground(new java.awt.Color(0, 255, 204));

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTable1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Guitar ID", "Guitar Brand", "GuitarType", "Year", "Price"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButtonDelete.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jButtonDelete.setText("Delete");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jButtonSortAsc.setText("Sort ASC");
        jButtonSortAsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSortAscActionPerformed(evt);
            }
        });

        jButtonSortDesc.setText("Sort DESC");
        jButtonSortDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSortDescActionPerformed(evt);
            }
        });

        jButtonUndo.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jButtonUndo.setText("Undo");
        jButtonUndo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUndoActionPerformed(evt);
            }
        });

        jButtonSearch.setText("Search");
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });

        jLabel1.setText("Sort By Year:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(jButtonDelete)
                .addGap(28, 28, 28)
                .addComponent(jButtonUndo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonSortDesc)
                    .addComponent(jButtonSortAsc))
                .addGap(32, 32, 32)
                .addComponent(jButtonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSearch)
                    .addComponent(jButtonSortAsc)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jButtonSortDesc)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonUndo)
                    .addComponent(jButtonDelete))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Browse Guitars", jPanel2);

        jPanel1.setBackground(new java.awt.Color(102, 255, 0));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Guitar ID:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Guitar Brand:");

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("GuitarType:");

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Price:");

        jButtonAdd.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jButtonAdd.setText("Add");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jButtonUpdate.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jButtonUpdate.setText("Update");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Year:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(176, 176, 176)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel2))
                                .addGap(13, 13, 13))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .addComponent(jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .addComponent(jTextField2)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonAdd)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonUpdate)))
                .addContainerGap(197, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAdd)
                    .addComponent(jButtonUpdate))
                .addContainerGap(168, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Guitar details", jPanel1);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel4.setText("Welcome");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel6.setText("To");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel8.setText("Guitar Hero");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel9.setText("Shop");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/guitar.png"))); // NOI18N
        jLabel11.setText("jLabel11");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel6))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel9)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addComponent(jLabel4))))
                .addGap(0, 52, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(88, 88, 88))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jTabbedPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel4, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
         try {
        int guitarId = Integer.parseInt(jTextField1.getText().trim());
        String brand = jTextField5.getText().trim();
        String type = jTextField6.getText().trim();
        int year = Integer.parseInt(jTextField2.getText().trim());
        double price = Double.parseDouble(jTextField4.getText().trim());

        if (brand.isEmpty() || type.isEmpty()) {
            JOptionPane.showMessageDialog(this, "All fields are required");
            return;
        }

        Guitar guitar = new Guitar(
                guitarId,
                brand,
                type,
                year,
                price       
        );

        // MVC: View → Controller
        boolean added = controller.addGuitar(guitar);

        if (!added) {
            JOptionPane.showMessageDialog(this, "Duplicate guitar");
            return;
        }

        // Update table (View responsibility)
        tableModel.addRow(new Object[]{
                guitarId,
                brand,
                type,
                year,
                price
        });

        clearFields();
        JOptionPane.showMessageDialog(this, "Guitar added successfully");

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Invalid number format for ID / Year / Price");

    } 
    }//GEN-LAST:event_jButtonAddActionPerformed
    private void seedInitialData() {

    if (!controller.getAllGuitars().isEmpty()) {
        return;
    }

    controller.addGuitar(new Guitar(1, "Fender", "Electric", 2018, 850));
    controller.addGuitar(new Guitar(2, "Gibson", "Electric", 2020, 2200));
    controller.addGuitar(new Guitar(3, "Ibanez", "Electric", 2016, 700));
    controller.addGuitar(new Guitar(4, "Martin", "Acoustic", 2019, 3000));
    controller.addGuitar(new Guitar(5, "Ibanez", "Bass", 2017, 650));
}



       private void loadTableFromInventory() {
        // Clear existing rows first
        tableModel.setRowCount(0);

        // Load all guitars from inventory into JTable
        for (Guitar g : controller.getAllGuitars()) {
        tableModel.addRow(new Object[]{
            g.getGuitarId(),
            g.getBrand(),
            g.getType(),
            g.getYear(),
            g.getPrice()
        });
    }
}
    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        try {
        int guitarId = Integer.parseInt(jTextField1.getText().trim());

        Guitar oldGuitar = controller.getGuitarById(guitarId);
        if (oldGuitar == null) {
            JOptionPane.showMessageDialog(this, "Guitar ID not found!");
            return;
        }

        String brand = jTextField5.getText().trim().isEmpty()
                ? oldGuitar.getBrand()
                : jTextField5.getText().trim();

        String type = jTextField6.getText().trim().isEmpty()
                ? oldGuitar.getType()
                : jTextField6.getText().trim();
        
        int year = jTextField2.getText().trim().isEmpty()
        ? oldGuitar.getYear()
        : Integer.parseInt(jTextField2.getText().trim());
        
        double price = jTextField4.getText().trim().isEmpty()
                ? oldGuitar.getPrice()
                : Double.parseDouble(jTextField4.getText().trim());

            Guitar updatedGuitar = new Guitar(
                guitarId,
                brand,
                type,
                year,
                price
            );



        boolean updated = controller.updateGuitar(updatedGuitar);
        if (!updated) {
            JOptionPane.showMessageDialog(this, "Update failed");
            return;
        }

        // Update JTable
        for (int i = 0; i < tableModel.getRowCount(); i++) {
            if ((int) tableModel.getValueAt(i, 0) == guitarId) {
                tableModel.setValueAt(brand, i, 1);
                tableModel.setValueAt(type, i, 2);
                tableModel.setValueAt(year, i, 3);
                tableModel.setValueAt(price, i, 4);
                break;
            }
        }

        clearFields();
        JOptionPane.showMessageDialog(this, "Guitar updated successfully!");

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Invalid ID or Price");
    }
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
         int selectedRow = jTable1.getSelectedRow();

    // 1️⃣ Check if any row is selected
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(
                this,
                "Please select a row to delete.",
                "No Selection",
                JOptionPane.WARNING_MESSAGE
        );
        return;
    }

   
    int confirm = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to delete this guitar?",
            "Confirm Delete",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
    );

    
    if (confirm != JOptionPane.YES_OPTION) {
        return;
    }

    
    int guitarId = Integer.parseInt(
            tableModel.getValueAt(selectedRow, 0).toString()
    );

    
    boolean deleted = controller.deleteGuitar(guitarId);
    

    if (!deleted) {
        JOptionPane.showMessageDialog(
                this,
                "Delete failed. Guitar not found.",
                "Error",
                JOptionPane.ERROR_MESSAGE
        );
        return;
    }

    
    tableModel.removeRow(selectedRow);

  
    JOptionPane.showMessageDialog(
            this,
            "Guitar deleted successfully!",
            "Success",
            JOptionPane.INFORMATION_MESSAGE
    );
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonUndoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUndoActionPerformed
         Guitar restored = controller.undoLastDelete();

    if (restored == null) {
        JOptionPane.showMessageDialog(
                this,
                "Nothing to undo",
                "Undo",
                JOptionPane.INFORMATION_MESSAGE
        );
        return;
    }

    loadTableFromInventory();

    JOptionPane.showMessageDialog(
            this,
            "Undo successful! Restored Guitar ID: " + restored.getGuitarId(),
            "Undo Complete",
            JOptionPane.INFORMATION_MESSAGE
    );
    }//GEN-LAST:event_jButtonUndoActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
         int row = jTable1.getSelectedRow();
    if (row == -1) return;

    jTextField1.setText(tableModel.getValueAt(row, 0).toString()); // ID
    jTextField5.setText(tableModel.getValueAt(row, 1).toString()); // Brand
    jTextField6.setText(tableModel.getValueAt(row, 2).toString()); // Type
    jTextField2.setText(tableModel.getValueAt(row, 3).toString()); // Year
    jTextField4.setText(tableModel.getValueAt(row, 4).toString()); // Price
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
        String input = jTextFieldSearch.getText().trim();

    if (input.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter Brand, Type, or Year");
        return;
    }

    
    if (input.matches("\\d+")) {
        int year = Integer.parseInt(input);

        Guitar found = controller.binarySearchByYear(year);

        if (found == null) {
            JOptionPane.showMessageDialog(this, "No guitar found for year: " + year);
            return;
        }

        JOptionPane.showMessageDialog(this,
                "Found:\nID: " + found.getGuitarId()
                + "\nBrand: " + found.getBrand()
                + "\nType: " + found.getType()
                + "\nPrice: " + found.getPrice()
        );
    }
    
    else {
        java.util.List<Guitar> results = controller.searchByKeyword(input);

        if (results.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No guitars found for: " + input);
            return;
        }

        loadTableFromList(results);

        JOptionPane.showMessageDialog(
                this,
                results.size() + " result(s) found for: " + input,
                "Search Complete",
                JOptionPane.INFORMATION_MESSAGE
        );
    }
    }//GEN-LAST:event_jButtonSearchActionPerformed

    private void jButtonSortAscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSortAscActionPerformed
        if (tableModel.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "No records to sort");
            return;
        }
        java.util.List<Guitar> sortedList =
        controller.getSortedGuitarsByYear();

        loadTableFromList(sortedList);

        JOptionPane.showMessageDialog(
            this,
            "Sorted by Year (Ascending)",
            "Sort Complete",
            JOptionPane.INFORMATION_MESSAGE
        );        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSortAscActionPerformed

    private void jButtonSortDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSortDescActionPerformed
        java.util.LinkedList<Guitar> sortedList =
        controller.getSortedGuitarsByYear();

        java.util.Collections.reverse(sortedList);

        loadTableFromList(sortedList);

        JOptionPane.showMessageDialog(
            this,
            "Sorted by Year (Descending)",
            "Sort Complete",
            JOptionPane.INFORMATION_MESSAGE
        );
    }//GEN-LAST:event_jButtonSortDescActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginPage().setVisible(true));
    }
private void clearFields() {
    jTextField1.setText("");
    jTextField5.setText("");
    jTextField6.setText("");
    jTextField2.setText("");
    jTextField4.setText("");

}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JButton jButtonSortAsc;
    private javax.swing.JButton jButtonSortDesc;
    private javax.swing.JButton jButtonUndo;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextFieldSearch;
    // End of variables declaration//GEN-END:variables
}
